---

- include_role:
    name: namespace
    tasks_from: create
  vars:
    name: "{{ che_namespace }}"
    display_name: "{{ che_display_name }}"
    monitor: true
    is_service: true

- include_tasks: download_installer.yml
- include_tasks: install.yml

- name: Set the launcher keycloak user as admin within the che deployment
  shell: "oc set env deployment/codeready CHE_SYSTEM_ADMIN__NAME={{launcher_sso_admin_username}} -n {{che_namespace}} --overwrite=true"
  register: set_kc_admin_env
  failed_when: set_kc_admin_env.rc != 0

- name: Wait for codeready
  shell: "oc rollout status deployment/codeready -n {{ che_namespace }}"


- name: "patch codeready deployment"
  shell: "oc patch deployment codeready --patch='{\"spec\":{\"replicas\": \" 0 \" }}' -n {{ che_namespace }}"
 

- name: Update Che configmap Java Options
  shell: "oc patch configmap che --patch '{\"data\":{\"CHE_WORKSPACE_JAVA__OPTIONS\": \" {{che_workspace_java__options}} \" }}' -n {{che_namespace}}"

- name: Update Che configmap Maven Options
  shell: "oc patch configmap che --patch '{\"data\":{\"CHE_WORKSPACE_MAVEN__OPTIONS\": \" {{che_workspace_maven__options}} \" }}' -n {{che_namespace}}"

 - name: "patch codeready deployment"
  shell: "oc patch deployment codeready --patch='{\"spec\":{\"replicas\": \" 1 \" }}' -n {{ che_namespace }}"
 


- name: Include keycloak tasks
  include_tasks: keycloak-client.yml
  when: che_multiuser|bool == true
